/* Build: inline the real SVG assets, then bundle+minify to dist/mozart-a11y.min.js */
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const SYM_DIR = path.join(__dirname, 'assets', 'symbols');

// symbols-N.svg -> control key. Mapping verified against Figma frame 22-4136
// (rendered contact sheet compared glyph-by-glyph, not by filename).
const MAP = {
  1: 'biggerInterface', 2: 'biggerText', 3: 'lineHeight', 4: 'textSpacing',
  5: 'readableFont', 6: 'textAlign', 7: 'contrast', 8: 'invert',
  9: 'grayscale', 10: 'saturation', 11: 'highlightLinks', 12: 'highlightTitles',
  13: 'readingGuide', 14: 'readingMask', 15: 'tooltips', 16: 'readAloud',
  17: 'pauseMotion', 18: 'hideImages', 19: 'muteSounds', 20: 'bigCursor',
  21: 'reset'
};

// White-filled glyphs -> recolour via `fill: currentColor`. Strip the root
// width/height so CSS controls size (viewBox preserved -> aspect ratio kept).
function normalize(svg) {
  svg = svg.replace(/<\?xml[^>]*\?>/g, '');
  // strip width/height on the FIRST <svg ...> tag only
  svg = svg.replace(/<svg\b[^>]*>/, function (tag) {
    return tag.replace(/\s(width|height)="[^"]*"/g, '')
              .replace('<svg', '<svg aria-hidden="true" focusable="false"');
  });
  svg = svg.replace(/fill="(#fff(fff)?|#FFF(FFF)?|white)"/g, 'fill="currentColor"');
  return svg.replace(/\s*\n\s*/g, '').trim();
}

const icons = {};
for (const [n, key] of Object.entries(MAP)) {
  icons[key] = normalize(fs.readFileSync(path.join(SYM_DIR, 'symbols-' + n + '.svg'), 'utf8'));
}
const logo = normalize(fs.readFileSync(path.join(__dirname, 'assets', 'logo_mozart.svg'), 'utf8'));

fs.writeFileSync(
  path.join(__dirname, 'src', 'assets.generated.js'),
  '/* AUTO-GENERATED by build.js from assets/. Do not edit by hand. */\n' +
  'export const ICON_SVGS = ' + JSON.stringify(icons) + ';\n' +
  'export const LOGO_SVG = ' + JSON.stringify(logo) + ';\n'
);

esbuild.buildSync({
  entryPoints: [path.join(__dirname, 'src', 'mozart-a11y.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  legalComments: 'inline',
  target: 'es2018',
  outfile: path.join(__dirname, 'dist', 'mozart-a11y.min.js')
});

const bytes = fs.statSync(path.join(__dirname, 'dist', 'mozart-a11y.min.js')).size;
console.log('built dist/mozart-a11y.min.js (' + bytes + ' bytes), ' + Object.keys(icons).length + ' glyphs + logo inlined');
